apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ2YWxheHlydHAwMy5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiYW1aeWIyZGZaRzlqYTJWeU9rQkNaVzVyZG1sbGJqRXdPVE09IgoJCX0KCX0KfQ==
kind: Secret
metadata:
  name: regcred
  namespace: valaxy
type: kubernetes.io/dockerconfigjson
